project:
  type: website

website:
  title: "Junaid Butt"
  description: "A personal blog built with Quarto"
  site-url: "https://JunaidMB.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: index.qmd
        text: Blog
      - href: study-notes.qmd
        text: Study Notes
      - href: cheatsheets.qmd
        text: Cheatsheets
    right:
      - icon: github
        href: https://github.com/JunaidMB
      - icon: linkedin
        href: https://linkedin.com/in/placeholder
  page-footer:
    left: "© 2024 Junaid Butt"
    right:
      - text: "Built with Quarto"
        href: https://quarto.org/

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-copy: true
    code-overflow: wrap

execute:
  freeze: auto