project:
  type: website
  render:
    - "*.qmd"
    - "!WRITER_GUIDE.md"

website:
  title: "Junaid Butt"
  description: "A personal blog built with Quarto"
  site-url: "https://JunaidMB.github.io"
  navbar:
    left:
      - href: index.qmd
        text: About Me
      - href: blog.qmd
        text: Blog
      - href: study-notes.qmd
        text: Study Notes
      - href: cheatsheets.qmd
        text: Cheatsheets
    right:
      - icon: github
        href: https://github.com/JunaidMB
      - icon: linkedin
        href: https://www.linkedin.com/in/junaid-butt-23a18314a

format:
  html:
    theme: cosmo
    css: styles.css
    code-copy: true
    code-overflow: wrap

execute:
  freeze: auto